server:
  port: 8080

spring:
  profiles: # Redis的账号密码
    active: secret
  main:
    allow-circular-references: true # 允许循环依赖
  jackson: # jackson格式源
    date-format: yyyy-mm-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  data:
    redis: # Redis数据源
      database: 0
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml

mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/*.xml
